import { Inter } from "next/font/google";
import "./globals.css";

// Configure Inter with weight 300
const inter = Inter({ 
  subsets: ["latin"],
  weight: "300", // This sets the light weight
  variable: "--font-inter", // Optional: used for CSS variables
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* Apply the font class to the body */}
      <body className={`${inter.className} antialiased text-[#333333]`}>
        {children}
      </body>
    </html>
  );
}